// Built-in preset configurations for popular AI API providers

export const PROVIDERS = {
  OPENAI: 'openai',
  ANTHROPIC: 'anthropic',
  GEMINI: 'gemini',
  OLLAMA: 'ollama',
  CUSTOM: 'custom',
  MOCK: 'mock',
}

export const DEFAULT_PRESETS = [
  {
    id: 'mock-agent',
    name: 'Mock AI Agent',
    provider: PROVIDERS.MOCK,
    icon: '🤖',
    color: '#6c63ff',
    endpoint: 'mock://internal',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'Authorization',
    apiKeyPrefix: 'Bearer',
    model: 'mock-gpt-4',
    systemPrompt: 'You are a helpful AI assistant.',
    temperature: 0.7,
    topP: 1.0,
    maxTokens: 2048,
    stream: true,
    customHeaders: {},
    tools: [],
    requestFormat: 'openai',
    description: 'ทดสอบ UI โดยไม่ต้องใช้ API Key จริง',
  },
  {
    id: 'openai-gpt4',
    name: 'OpenAI GPT',
    provider: PROVIDERS.OPENAI,
    icon: '⚡',
    color: '#00d2ff',
    endpoint: 'https://api.openai.com/v1/chat/completions',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'Authorization',
    apiKeyPrefix: 'Bearer',
    model: 'gpt-4o',
    systemPrompt: 'You are a helpful assistant.',
    temperature: 0.7,
    topP: 1.0,
    maxTokens: 4096,
    stream: true,
    customHeaders: {},
    tools: [],
    requestFormat: 'openai',
    description: 'OpenAI Chat Completions API — GPT-4o, GPT-4, GPT-3.5',
  },
  {
    id: 'anthropic-claude',
    name: 'Anthropic Claude',
    provider: PROVIDERS.ANTHROPIC,
    icon: '🧠',
    color: '#ff7b2f',
    endpoint: 'https://api.anthropic.com/v1/messages',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'x-api-key',
    apiKeyPrefix: '',
    model: 'claude-opus-4-5',
    systemPrompt: 'You are Claude, an AI assistant made by Anthropic.',
    temperature: 1.0,
    topP: 1.0,
    maxTokens: 8192,
    stream: true,
    customHeaders: {
      'anthropic-version': '2023-06-01',
      'anthropic-beta': 'interleaved-thinking-2025-05-14',
    },
    tools: [],
    requestFormat: 'anthropic',
    description: 'Anthropic Messages API — Claude Opus, Sonnet, Haiku',
  },
  {
    id: 'gemini-pro',
    name: 'Google Gemini',
    provider: PROVIDERS.GEMINI,
    icon: '✨',
    color: '#00ff9d',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'x-goog-api-key',
    apiKeyPrefix: '',
    model: 'gemini-2.0-flash',
    systemPrompt: 'You are a helpful AI assistant.',
    temperature: 1.0,
    topP: 0.95,
    maxTokens: 8192,
    stream: true,
    customHeaders: {},
    tools: [],
    requestFormat: 'gemini',
    description: 'Google Gemini API — Gemini 2.0 Flash, Pro',
  },
  {
    id: 'ollama-local',
    name: 'Ollama (Local)',
    provider: PROVIDERS.OLLAMA,
    icon: '🦙',
    color: '#ffb700',
    endpoint: 'http://localhost:11434/api/chat',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'Authorization',
    apiKeyPrefix: 'Bearer',
    model: 'llama3.2',
    systemPrompt: 'You are a helpful assistant.',
    temperature: 0.7,
    topP: 1.0,
    maxTokens: 4096,
    stream: true,
    customHeaders: {},
    tools: [],
    requestFormat: 'ollama',
    description: 'Ollama Local API — Llama, Mistral, Phi, Qwen และอื่นๆ',
  },
  {
    id: 'custom-api',
    name: 'Custom Endpoint',
    provider: PROVIDERS.CUSTOM,
    icon: '🔧',
    color: '#ff4d6d',
    endpoint: 'https://your-api.example.com/v1/chat',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'Authorization',
    apiKeyPrefix: 'Bearer',
    model: 'custom-model',
    systemPrompt: '',
    temperature: 0.7,
    topP: 1.0,
    maxTokens: 2048,
    stream: false,
    customHeaders: {},
    tools: [],
    requestFormat: 'openai',
    description: 'กำหนดค่า API Endpoint เองได้ทั้งหมด',
  },
]

export const REQUEST_FORMATS = {
  openai: 'OpenAI Format',
  anthropic: 'Anthropic Format',
  gemini: 'Gemini Format',
  ollama: 'Ollama Format',
}

export function createPreset(overrides = {}) {
  return {
    id: `preset-${Date.now()}`,
    name: 'New Preset',
    provider: PROVIDERS.CUSTOM,
    icon: '🔧',
    color: '#6c63ff',
    endpoint: '',
    method: 'POST',
    apiKey: '',
    apiKeyHeader: 'Authorization',
    apiKeyPrefix: 'Bearer',
    model: '',
    systemPrompt: '',
    temperature: 0.7,
    topP: 1.0,
    maxTokens: 2048,
    stream: false,
    customHeaders: {},
    tools: [],
    requestFormat: 'openai',
    description: '',
    ...overrides,
  }
}
